"""
Retrieval query expansion engine.

Transforms a single user topic into a ranked list of Tavily-optimised search
queries without any LLM calls.  Queries are generated by combining the topic
with domain-specific angles (authority, trend, implementation, tutorial, etc.)
drawn from retrieval_config.py trusted-source data.

Replaces the purely educational ``topic_expansion_service`` pattern for the
retrieval path.  ``topic_expansion_service`` (learning graph: prerequisites,
related_topics, progressions) is preserved separately for the UI/chat layer.

Design constraints
------------------
- Zero I/O — pure string operations, no DB, no API calls.
- Mode-aware limits: chat 1–2, feed 2–4, deep_research 4–6.
- Retrieval-first: every query angle is designed to surface documents, not
  explain concepts.
- Trusted-source preference: authority angles embed known source names so
  Tavily's ranking surfaces them even without ``include_domains``.

Public API
----------
expand_queries(topic, mode)           → ExpansionResult
get_query_strings(topic, mode)        → list[str]   convenience wrapper
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

# ── Mode query-count limits ───────────────────────────────────────────────────

_MODE_LIMITS: dict[str, int] = {
    "chat":          2,
    "feed":          4,
    "deep_research": 6,
}

_DEFAULT_LIMIT = 2


# ── Query angle descriptor ────────────────────────────────────────────────────

@dataclass(frozen=True)
class _QueryAngle:
    """
    Template for one retrieval angle.

    ``template``    — Python format string with a ``{topic}`` placeholder.
                      May also use ``{base}`` (connector-stripped form).
    ``angle``       — human label: "primary" | "authority" | "trend" |
                      "implementation" | "tutorial" | "comparison" | "report"
    ``priority``    — lower = more important; determines selection order within
                      a mode's query budget.
    ``source_hint`` — optional trusted domain this query targets (metadata only;
                      the router applies include_domains separately).
    """
    template:    str
    angle:       str
    priority:    int
    source_hint: str | None = None


# ── Domain-specific angle tables ──────────────────────────────────────────────
#
# Rules per domain (from spec):
#   AI/Tech      → implementation, architecture, benchmark, GitHub, arXiv, HuggingFace
#   Finance      → annual report, SEC filing, market trends, McKinsey analysis
#   Pharma       → FDA, WHO, manufacturing, supply chain, exports
#   Manufacturing→ industry 4.0, lean/ISO, OEE, automation, McKinsey operations
#   Export/Trade → WTO, customs, tariffs, World Bank
#   Business     → McKinsey/BCG/HBR, case studies, strategy frameworks
#
# Priority order (lower = picked first when mode budget is tight):
#   1 primary  → bare topic (highest Tavily cache hit probability)
#   2 authority → trusted source + topic (high signal-to-noise)
#   3 trend     → topic + year/developments (freshness)
#   4 impl/spec → topic + action term (depth)
#   5 tutorial  → topic + tutorial/guide (breadth)
#   6 alt       → topic + comparative/extra angle (discovery)

_DOMAIN_ANGLES: dict[str, list[_QueryAngle]] = {

    "ai": [
        _QueryAngle("{topic}",                                          "primary",        1),
        _QueryAngle("{topic} arxiv paper 2025",                         "authority",      2, "arxiv.org"),
        _QueryAngle("{topic} state of the art benchmark results",        "benchmark",      3, "paperswithcode.com"),
        _QueryAngle("{topic} implementation pytorch tutorial",           "tutorial",       4, "huggingface.co"),
        _QueryAngle("{topic} latest research developments 2025",         "trend",          5),
        _QueryAngle("{topic} huggingface model fine-tuning deployment",  "implementation", 6, "huggingface.co"),
    ],

    "technology": [
        _QueryAngle("{topic}",                                                   "primary",        1),
        _QueryAngle("{topic} official documentation getting started",             "authority",      2),
        _QueryAngle("{topic} github open source implementation",                  "implementation", 3, "github.com"),
        _QueryAngle("{topic} architecture best practices scalability 2025",        "architecture",   4),
        _QueryAngle("{topic} comparison alternatives benchmark performance",       "comparison",     5),
        _QueryAngle("{topic} tutorial step-by-step guide beginner",               "tutorial",       6),
    ],

    "finance": [
        _QueryAngle("{topic}",                                                    "primary",    1),
        _QueryAngle("{topic} SEC filing annual report earnings 2025",              "authority",  2, "sec.gov"),
        _QueryAngle("{topic} market trends capital markets outlook 2025",          "trend",      3),
        _QueryAngle("{topic} McKinsey BCG analysis strategic outlook",             "report",     4, "mckinsey.com"),
        _QueryAngle("{topic} regulatory compliance risk update 2025",              "regulatory", 5, "federalreserve.gov"),
        _QueryAngle("{topic} quantitative research risk factor model",             "research",   6),
    ],

    "pharma": [
        _QueryAngle("{topic}",                                                    "primary",    1),
        _QueryAngle("{topic} FDA clinical trial approval 2025",                    "authority",  2, "fda.gov"),
        _QueryAngle("{topic} PubMed research paper clinical evidence",             "research",   3, "pubmed.ncbi.nlm.nih.gov"),
        _QueryAngle("{topic} WHO guidelines drug supply chain",                    "authority",  4, "who.int"),
        _QueryAngle("{topic} EMA ICH regulatory pathway approval",                 "regulatory", 5, "ema.europa.eu"),
        _QueryAngle("{topic} drug pipeline manufacturing exports outlook 2025",    "trend",      6),
    ],

    "manufacturing": [
        _QueryAngle("{topic}",                                                    "primary",        1),
        _QueryAngle("{topic} industry 4.0 automation smart factory 2025",          "trend",          2),
        _QueryAngle("{topic} lean six sigma ISO standard OEE benchmark",           "standard",       3, "iso.org"),
        _QueryAngle("{topic} predictive maintenance implementation ROI",            "implementation", 4),
        _QueryAngle("{topic} McKinsey operations supply chain report",              "report",         5, "mckinsey.com"),
        _QueryAngle("{topic} industrial IoT robotics production analytics",         "technology",     6),
    ],

    "export_trade": [
        _QueryAngle("{topic}",                                                    "primary",    1),
        _QueryAngle("{topic} WTO trade policy tariff update 2025",                 "authority",  2, "wto.org"),
        _QueryAngle("{topic} customs compliance HS code regulation guide",         "compliance", 3),
        _QueryAngle("{topic} World Bank trade data logistics analysis",             "data",       4, "worldbank.org"),
        _QueryAngle("{topic} global trade outlook freight costs 2025",             "trend",      5),
        _QueryAngle("{topic} export opportunity emerging market DGFT",             "strategy",   6),
    ],

    "business": [
        _QueryAngle("{topic}",                                                    "primary",    1),
        _QueryAngle("{topic} McKinsey BCG strategy framework analysis 2025",        "report",     2, "mckinsey.com"),
        _QueryAngle("{topic} Harvard Business Review case study insights",          "authority",  3, "hbr.org"),
        _QueryAngle("{topic} market analysis competitive landscape 2025",           "trend",      4),
        _QueryAngle("{topic} business model execution OKR strategy",               "framework",  5),
        _QueryAngle("{topic} startup venture case study examples",                  "case_study", 6),
    ],

    "default": [
        _QueryAngle("{topic}",                             "primary",  1),
        _QueryAngle("{topic} overview guide 2025",          "overview", 2),
        _QueryAngle("{topic} practical examples tutorial",  "tutorial", 3),
    ],
}


# ── Output types ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ExpandedQuery:
    text:        str
    angle:       str             # angle label from _QueryAngle
    source_hint: str | None      # trusted domain this query targets (if any)
    priority:    int


@dataclass
class ExpansionResult:
    topic:      str
    domain_key: str
    mode:       str
    queries:    list[ExpandedQuery]  # ordered by priority, length = mode limit

    def query_strings(self) -> list[str]:
        """Return just the query text strings, preserving priority order."""
        return [q.text for q in self.queries]

    def authority_queries(self) -> list[ExpandedQuery]:
        """Return only queries targeting a known trusted source."""
        return [q for q in self.queries if q.source_hint]


# ── Topic normalisation ───────────────────────────────────────────────────────

# Connector words that add noise without improving retrieval precision.
_CONNECTORS = re.compile(
    r"\b(in|for|the|of|and|or|with|using|via|by|from|to|at|a|an|about)\b",
    re.IGNORECASE,
)


def _normalize(topic: str) -> str:
    """
    Strip connector words and collapse whitespace.

    "AI in manufacturing" → "AI manufacturing"
    "deep learning for healthcare" → "deep learning healthcare"
    """
    cleaned = _CONNECTORS.sub(" ", topic.strip())
    return re.sub(r"\s{2,}", " ", cleaned).strip()


# ── Domain resolution ─────────────────────────────────────────────────────────

def _resolve_domain(topic: str) -> str:
    """
    Classify topic into a retrieval_config key without importing the full
    domain_classifier (avoids circular dependency at module load time).
    """
    from .retrieval_router import multi_classify   # deferred
    return multi_classify(topic).primary.domain_key


# ── Core expansion logic ──────────────────────────────────────────────────────

def expand_queries(topic: str, mode: str = "chat") -> ExpansionResult:
    """
    Expand a topic into a ranked list of Tavily-optimised retrieval queries.

    Parameters
    ----------
    topic   User query or topic string (any length).
    mode    "chat" | "feed" | "deep_research"  — controls query budget.

    Returns
    -------
    ExpansionResult whose ``.queries`` list is at most ``_MODE_LIMITS[mode]``
    entries, ordered by priority (most important first).

    The function never raises — a minimal one-query result is always returned.
    """
    limit      = _MODE_LIMITS.get(mode, _DEFAULT_LIMIT)
    domain_key = _resolve_domain(topic)
    base       = _normalize(topic)

    angles = _DOMAIN_ANGLES.get(domain_key, _DOMAIN_ANGLES["default"])
    # Sort by priority so the budget truncation always keeps the best queries.
    sorted_angles = sorted(angles, key=lambda a: a.priority)

    expanded: list[ExpandedQuery] = []
    seen_texts: set[str] = set()

    for angle in sorted_angles:
        if len(expanded) >= limit:
            break

        try:
            text = angle.template.format(topic=topic, base=base).strip()
        except KeyError:
            text = angle.template.replace("{topic}", topic).replace("{base}", base).strip()

        # Deduplicate — can happen when topic == base
        norm_text = re.sub(r"\s+", " ", text.lower())
        if norm_text in seen_texts:
            continue
        seen_texts.add(norm_text)

        expanded.append(ExpandedQuery(
            text        = text,
            angle       = angle.angle,
            source_hint = angle.source_hint,
            priority    = angle.priority,
        ))

    # Safety: always return at least the raw topic
    if not expanded:
        expanded = [ExpandedQuery(text=topic, angle="primary", source_hint=None, priority=1)]

    return ExpansionResult(
        topic      = topic,
        domain_key = domain_key,
        mode       = mode,
        queries    = expanded,
    )


# ── Convenience accessor ──────────────────────────────────────────────────────

def get_query_strings(topic: str, mode: str = "chat") -> list[str]:
    """
    Return just the query strings for a topic and mode.

    Convenience wrapper around ``expand_queries`` for callers that don't
    need the full ``ExpansionResult`` metadata.
    """
    return expand_queries(topic, mode).query_strings()
