"""
Structured research report generation.

Transforms deep-research JSON (produced by DeepResearchWorkflow) into a
professional, multi-section report.  No additional AI calls are made — all
content is derived from data already generated by the deep-research pipeline.

Report sections
---------------
  executive_summary   — synthesised from research_summary + top implication
  key_findings        — from key_findings + viewpoint stances when sparse
  trend_analysis      — trends_identified + momentum score (pure-code)
  opportunities       — strategic_implications + practical_applications
  risks               — tradeoffs + open questions framed as uncertainties
  important_resources — source URLs classified and sorted by credibility tier
  source_references   — raw URL list

Public API
----------
generate_report(topic, research_data, industry_data=None) → dict
format_report_as_markdown(report)                          → str
format_report_as_text(report)                              → str
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from urllib.parse import urlparse

# ── Momentum vocabulary ────────────────────────────────────────────────────────

_ACCELERATING_WORDS = frozenset({
    "rapidly", "accelerating", "explosive", "surge", "boom", "skyrocket",
    "unprecedented", "breakthrough", "revolutionary", "exponential",
    "growing", "emerging", "rising", "expanding", "increasing", "latest",
    "new", "novel", "launches", "announces", "introduces",
})
_DECLINING_WORDS = frozenset({
    "declining", "slowing", "plateau", "shrinking", "stagnant",
    "saturated", "legacy", "obsolete", "mature", "deprecated",
})

# ── Source-type classification ────────────────────────────────────────────────

_ACADEMIC_NETLOCS = frozenset({
    "arxiv.org", "pubmed.ncbi.nlm.nih.gov", "nature.com", "science.org",
    "biorxiv.org", "ieee.org", "acm.org", "semanticscholar.org",
    "springer.com", "papers.nips.cc", "proceedings.mlr.press",
    "wiley.com", "tandfonline.com", "researchgate.net",
})
_PRACTITIONER_NETLOCS = frozenset({
    "github.com", "stackoverflow.com", "medium.com", "dev.to",
    "huggingface.co", "paperswithcode.com", "pytorch.org",
    "tensorflow.org", "readthedocs.io", "docs.python.org",
    "developer.mozilla.org", "towardsdatascience.com",
})
_NEWS_NETLOCS = frozenset({
    "techcrunch.com", "wired.com", "theverge.com", "bloomberg.com",
    "reuters.com", "ft.com", "wsj.com", "venturebeat.com",
    "ars technica.com", "zdnet.com", "businessinsider.com",
})
_OFFICIAL_SUFFIXES = (".gov", ".edu", ".int", ".mil")
_OFFICIAL_NETLOCS  = frozenset({"who.int", "nih.gov", "fda.gov", "iso.org", "worldbank.org"})

_TIER_ORDER = {"academic": 0, "official": 1, "practitioner": 2, "news": 3, "general": 4}


def _classify_url(url: str) -> str:
    try:
        netloc = urlparse(url).netloc.lower().removeprefix("www.")
    except Exception:
        return "general"
    if netloc in _ACADEMIC_NETLOCS:
        return "academic"
    if netloc in _PRACTITIONER_NETLOCS:
        return "practitioner"
    if netloc in _NEWS_NETLOCS:
        return "news"
    if netloc in _OFFICIAL_NETLOCS or any(netloc.endswith(s) for s in _OFFICIAL_SUFFIXES):
        return "official"
    return "general"


# ═══════════════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════════════

def generate_report(
    topic: str,
    research_data: dict,
    industry_data: dict | None = None,
) -> dict:
    """
    Build a structured report dict from deep-research JSON.

    Accepts the full output of DeepResearchWorkflow.run() as *research_data*
    and optionally enriches opportunities with industry_intelligence data.

    Return shape
    ------------
    {
      "title":            str,
      "topic":            str,
      "generated_at":     str (ISO 8601),
      "confidence_level": str,
      "sections": {
        "executive_summary":   str,
        "key_findings":        list[str],
        "trend_analysis":      {"trends": list[str], "momentum": str},
        "opportunities":       list[str],
        "risks":               list[str],
        "important_resources": list[{"url": str, "type": str}],
        "source_references":   list[str],
      },
      "appendix": {
        "related_concepts":    list[str],
        "open_questions":      list[str],
        "advanced_follow_ups": list[str],
      },
    }
    """
    return {
        "title":            f"Research Report: {topic.strip().title()}",
        "topic":            topic,
        "generated_at":     datetime.now(timezone.utc).isoformat(),
        "confidence_level": research_data.get("confidence_level", "medium"),
        "sections": {
            "executive_summary":   _build_executive_summary(research_data, industry_data),
            "key_findings":        _extract_key_findings(research_data),
            "trend_analysis":      _build_trend_analysis(research_data),
            "opportunities":       _extract_opportunities(research_data, industry_data),
            "risks":               _extract_risks(research_data),
            "important_resources": _build_resource_list(research_data),
            "source_references":   [u for u in research_data.get("sources", []) if u],
        },
        "appendix": {
            "related_concepts":    research_data.get("related_concepts",    []),
            "open_questions":      research_data.get("open_questions",      []),
            "advanced_follow_ups": research_data.get("advanced_follow_ups", []),
        },
    }


def format_report_as_markdown(report: dict) -> str:
    """Render a report dict as professional, readable markdown."""
    s   = report["sections"]
    app = report["appendix"]
    conf  = _confidence_label(report.get("confidence_level", "medium"))
    dated = _fmt_date(report.get("generated_at", ""))

    lines: list[str] = [
        f"# {report['title']}",
        "",
        f"**Confidence:** {conf} &nbsp;|&nbsp; **Generated:** {dated}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        s["executive_summary"],
        "",
        "---",
        "",
        "## Key Findings",
        "",
    ]

    for i, finding in enumerate(s["key_findings"], 1):
        lines.append(f"{i}. {finding}")

    lines += ["", "---", "", "## Trend Analysis", ""]
    ta = s["trend_analysis"]
    lines.append(f"**Market Momentum:** {ta['momentum'].capitalize()}")
    lines.append("")
    for trend in ta.get("trends", []):
        lines.append(f"- {trend}")

    lines += ["", "---", "", "## Opportunities & Risks", "", "### Opportunities", ""]
    for opp in s["opportunities"]:
        lines.append(f"- {opp}")

    lines += ["", "### Risks & Uncertainties", ""]
    for risk in s["risks"]:
        lines.append(f"- {risk}")

    lines += ["", "---", "", "## Important Resources", ""]
    if s["important_resources"]:
        lines.append("| Source | Type |")
        lines.append("|--------|------|")
        for res in s["important_resources"]:
            label = _url_label(res["url"])
            lines.append(f"| [{label}]({res['url']}) | {res['type'].capitalize()} |")
    else:
        lines.append("_No sources retrieved._")

    lines += ["", "---", "", "## Source References", ""]
    for i, url in enumerate(s["source_references"], 1):
        lines.append(f"{i}. {url}")

    if any(app.values()):
        lines += ["", "---", "", "## Appendix", ""]
        if app.get("related_concepts"):
            lines.append("**Related Concepts:** " + ", ".join(app["related_concepts"]))
            lines.append("")
        if app.get("open_questions"):
            lines.append("**Open Questions:**")
            for q in app["open_questions"]:
                lines.append(f"- {q}")
            lines.append("")
        if app.get("advanced_follow_ups"):
            lines.append("**Advanced Follow-up Topics:**")
            for t in app["advanced_follow_ups"]:
                lines.append(f"- {t}")

    return "\n".join(lines)


def format_report_as_text(report: dict) -> str:
    """Plain-text version — strips markdown syntax for terminal or email use."""
    md   = format_report_as_markdown(report)
    text = re.sub(r"^#{1,6}\s+", "", md, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"&nbsp;", " ", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"^\|.+\|$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^---+$", "─" * 60, text, flags=re.MULTILINE)
    return text.strip()


# ═══════════════════════════════════════════════════════════════════════════════
# Section builders (internal, exposed for testing)
# ═══════════════════════════════════════════════════════════════════════════════

def _build_executive_summary(research_data: dict, industry_data: dict | None) -> str:
    """
    Synthesise executive summary from existing AI-generated fields.

    Pure text composition — no AI call.  Combines research_summary,
    top strategic implication, optional industry context, and a
    confidence-calibration sentence.
    """
    parts: list[str] = []

    summary = research_data.get("research_summary", "").strip()
    if summary:
        parts.append(summary)

    implications = research_data.get("strategic_implications", [])
    if implications:
        cleaned = re.sub(r"^Implication \d+\s*[—\-]\s*[^:]+:\s*", "", implications[0]).strip()
        if cleaned:
            parts.append(f"Strategically, {cleaned}")

    if industry_data:
        trend_summary = industry_data.get("trend_summary", "").strip()
        if trend_summary:
            parts.append(f"Industry context: {trend_summary}")

    confidence_note = {
        "high":   "This analysis is supported by multiple converging sources.",
        "medium": "This analysis reflects mixed signals from available sources.",
        "low":    "This analysis is based on limited source material and should be treated as preliminary.",
    }.get(research_data.get("confidence_level", "medium"), "")
    if confidence_note:
        parts.append(confidence_note)

    return " ".join(parts) if parts else "No summary available."


def _extract_key_findings(research_data: dict) -> list[str]:
    """
    Return key findings list; augments with viewpoint stances when sparse.
    """
    findings = list(research_data.get("key_findings", []))

    if len(findings) < 3:
        for vp in research_data.get("viewpoint_comparison", [])[:2]:
            stance = vp.get("stance", "").strip()
            label  = vp.get("perspective", "")
            if stance:
                findings.append(f"[{label}] {stance}" if label else stance)

    return findings[:8]


def _build_trend_analysis(research_data: dict) -> dict:
    trends   = research_data.get("trends_identified", [])
    momentum = _score_momentum(trends + [research_data.get("research_summary", "")])
    return {"trends": trends, "momentum": momentum}


def _extract_opportunities(research_data: dict, industry_data: dict | None) -> list[str]:
    opps: list[str] = []

    for imp in research_data.get("strategic_implications", [])[:3]:
        cleaned = re.sub(r"^Implication \d+\s*[—\-]\s*[^:]+:\s*", "", imp).strip()
        if cleaned:
            opps.append(cleaned)

    for app in research_data.get("practical_applications", [])[:3]:
        cleaned = re.sub(r"^[Aa]pplication \d+:?\s*", "", app).strip()
        if cleaned and cleaned not in opps:
            opps.append(cleaned)

    if industry_data:
        for opp in industry_data.get("emerging_opportunities", [])[:2]:
            label = opp.get("opportunity", "").strip()
            if label and label not in opps:
                opps.append(label)

    return opps[:8]


def _extract_risks(research_data: dict) -> list[str]:
    risks: list[str] = []

    for tradeoff in research_data.get("tradeoffs", [])[:3]:
        dimension = tradeoff.get("dimension", "").strip()
        verdict   = tradeoff.get("verdict", "").strip()
        if dimension:
            entry = f"{dimension}: {verdict}" if verdict else dimension
            risks.append(entry)

    for q in research_data.get("open_questions", [])[:3]:
        cleaned = re.sub(r"^Question \d+\s*[—\-]\s*[^:]+:\s*", "", q).strip()
        if cleaned:
            risks.append(f"Unresolved: {cleaned}")

    return risks[:6]


def _build_resource_list(research_data: dict) -> list[dict]:
    seen: set[str] = set()
    resources: list[dict] = []

    for url in research_data.get("sources", []):
        if not url or url in seen:
            continue
        seen.add(url)
        resources.append({"url": url, "type": _classify_url(url)})

    resources.sort(key=lambda r: _TIER_ORDER.get(r["type"], 5))
    return resources[:10]


# ═══════════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def _score_momentum(texts: list[str]) -> str:
    combined = " ".join(texts).lower()
    words    = set(re.sub(r"[^\w\s]", " ", combined).split())
    accel    = len(words & _ACCELERATING_WORDS)
    decline  = len(words & _DECLINING_WORDS)
    if accel > decline + 1:
        return "accelerating"
    if decline > accel + 1:
        return "declining"
    return "stable"


def _confidence_label(level: str) -> str:
    return {"high": "High ✓", "medium": "Medium", "low": "Low ⚠"}.get(level, "Medium")


def _fmt_date(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return dt.strftime("%B %d, %Y")
    except Exception:
        return iso[:10] if len(iso) >= 10 else "Unknown"


def _url_label(url: str) -> str:
    try:
        parsed = urlparse(url)
        netloc = parsed.netloc.removeprefix("www.")
        last   = parsed.path.rstrip("/").split("/")[-1]
        label  = last.replace("-", " ").replace("_", " ").strip()
        return f"{netloc} — {label}" if label else netloc
    except Exception:
        return url[:60]
